version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P ${MYSQL_DOCKER_PORT} -u ${MYSQLDB_USER} -p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: online-book-store
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQL_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC",
      "spring.datasource.username": "${MYSQLDB_USER}", 
      "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}", 
      "jwt.secret": "${jwt_secret}",
      "jwt.expiration": "${jwt_expiration}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - ./.env
